# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-21 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
