# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-25 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180825_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='host_name',
            new_name='name',
        ),
    ]
