# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-03 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0002_auto_20180903_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault2tag',
            options={'verbose_name': '故障-标签', 'verbose_name_plural': '故障-标签'},
        ),
    ]
