# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-03 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0003_auto_20180903_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultreport',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='up_count',
            field=models.IntegerField(default=0),
        ),
    ]
