# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fault_reporting', '0007_auto_20180904_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultdetail',
            name='content',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
